name: X-Test
on: [push]
jobs:
  xtest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Triiger workflow_file_name
        run: |
          curl -X POST \
               -u "${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -H "Content-Type:application/json" \
               https://api.github.com/repos/opentdf/backend/actions/workflows/xtest.yaml/dispatches \
               --data '{"ref": "main"}'
    # - uses: convictional/trigger-workflow-and-wait@v1.6.0
    #   with:
    #     owner: ${{ github.repository_owner }}
    #     repo: opentdf/backend
    #     github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    #     workflow_file_name: xtest.yaml