name: X-Test
on: [push]
jobs:
  xtest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Trigger opentdf/backend/xtest python
        run: |
          curl -X POST \
               -u "${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/opentdf/backend/dispatches \
               --data '{"event_type":"xtest"}'
